# -*- coding: utf-8 -*-
"""Pay & Park Collection - Park 360.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XszpitHumDMTZvsyKHYsPxjPltSgWemG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ppc = pd.read_excel('/Pay_Park_Collection_Report.xlsx')

ppc

ppc.info()

# total rows and cols

print(f"Number of rows: {ppc.shape[0]}")
print(f"Number of columns: {ppc.shape[1]}")

missing_values = ppc[["Extra Transactionid Out", "Paymentstatus Out", "Ticket Loss Amount", "Vehicle Exit Medium"]].isnull().sum()
print(missing_values)

#fill missing values.

ppc['Extra Transactionid Out'] = ppc['Extra Transactionid Out'].fillna('Unknown')

print(f"Missing values in 'Extra Transactionid Out' after filling: {ppc['Extra Transactionid Out'].isnull().sum()}")

ppc['Ticket Loss Amount'] = ppc['Ticket Loss Amount'].fillna(0)

print(f"Missing values in 'Ticket Loss Amount' after filling: {ppc['Ticket Loss Amount'].isnull().sum()}")

mode_vehicle_exit_medium = ppc['Vehicle Exit Medium'].mode()[0]
ppc['Vehicle Exit Medium'] = ppc['Vehicle Exit Medium'].fillna(mode_vehicle_exit_medium)

print(f"Missing values in 'Vehicle Exit Medium' after filling: {ppc['Vehicle Exit Medium'].isnull().sum()}")

mode_paymentstatus = ppc['Paymentstatus Out'].mode()[0]
ppc['Paymentstatus Out'] = ppc['Paymentstatus Out'].fillna(mode_paymentstatus)

print(f"Missing values in 'Paymentstatus Out' after filling: {ppc['Paymentstatus Out'].isnull().sum()}")

ppc['Intime'] = pd.to_datetime(ppc['Intime'], format='%d-%m-%Y %I:%M:%S %p')
ppc['Outtime'] = pd.to_datetime(ppc['Outtime'], format='%d-%m-%Y %I:%M:%S %p')

print("Data types after conversion:")
ppc.info()

# stay duration per vehicle

ppc['Duration'] = ppc['Outtime'] - ppc['Intime']
display(ppc.head())

#vehicle count by type of vehicle

vehicle_type_counts = ppc['Vehicletype'].value_counts()
print("Vehicle Type Counts:")
display(vehicle_type_counts)

#average_duration_by_vehicle_type

average_duration_by_vehicle_type = ppc.groupby('Vehicletype')['Duration'].mean()
print("Average Duration by Vehicle Type:")
display(average_duration_by_vehicle_type)

total_revenue = ppc['Amount'].sum()
print(f"Total Parking Revenue: {total_revenue}")

total_initial_amount = ppc['Initial Amount'].sum()
print(f"Total Initial Amount: {total_initial_amount}")

total_extra_amount = ppc['Extra Amount'].sum()
print(f"Total Extra Amount: {total_extra_amount}")

payment_status_counts = ppc['Paymentstatus Out'].value_counts()
print("Payment Status Counts:")
display(payment_status_counts)

#total_ticket_loss

total_ticket_loss = ppc['Ticket Loss Amount'].sum()
print(f"Total Ticket Loss Amount: {total_ticket_loss}")

ticket_loss_stats = ppc['Ticket Loss Amount'].describe()
print("Descriptive Statistics for Ticket Loss Amount:")
display(ticket_loss_stats)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(ppc['Ticket Loss Amount'], bins=30, kde=True)
plt.title('Distribution of Ticket Loss Amount')
plt.xlabel('Ticket Loss Amount')
plt.ylabel('Frequency')
plt.show()



"""# Task
Analyze vehicle entry patterns by extracting the hour from the 'Intime' column in the `ppc` DataFrame, calculating the number of entries per hour, identifying peak entry hours, and visualizing the hourly entry counts using a bar plot.

## Extract entry hour

### Subtask:
Extract the hour from the 'Intime' column and create a new column for it.

**Reasoning**:
The subtask is to extract the hour from the 'Intime' column and store it in a new column called 'Entry Hour'. I will use the `.dt.hour` accessor for this.
"""

ppc['Entry Hour'] = ppc['Intime'].dt.hour
print("Extracted 'Entry Hour' from 'Intime' column.")
print(ppc[['Intime', 'Entry Hour']].head())

"""## Calculate hourly entry counts

### Subtask:
Calculate the number of vehicle entries for each hour of the day.

**Reasoning**:
To calculate the number of vehicle entries for each hour of the day, I will group the DataFrame by 'Entry Hour' and count the occurrences in each group.
"""

#Number of vehicle entries per hour:

hourly_entries = ppc.groupby('Entry Hour').size()
print("Number of vehicle entries per hour:")
display(hourly_entries)

"""## Identify peak entry hours

### Subtask:
Identify the hour(s) with the highest number of vehicle entries.

**Reasoning**:
To identify the peak entry hour(s), I need to find the maximum value in the `hourly_entries` Series and then retrieve the index (hour) associated with that maximum value.
"""

peak_entry_hours = hourly_entries[hourly_entries == hourly_entries.max()].index.tolist()
peak_entry_count = hourly_entries.max()
print(f"Peak entry hour(s): {peak_entry_hours} with {peak_entry_count} entries.")

"""## Visualize hourly entry counts

### Subtask:
Create a bar plot to visualize the number of vehicle entries per hour.

**Reasoning**:
To visualize the hourly entry counts, I will create a bar plot using `seaborn` and `matplotlib.pyplot`. This will clearly show the distribution of vehicle entries throughout the day.
"""

plt.figure(figsize=(12, 6))
sns.barplot(x=hourly_entries.index, y=hourly_entries.values, palette='viridis')
plt.title('Number of Vehicle Entries per Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Entries')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**Reasoning**:
The previous code generated a `FutureWarning` because `palette` was passed without assigning `hue`. To fix this, I will assign the `x` variable to `hue` and set `legend=False` as suggested by the warning, while also explicitly defining the color palette. This will suppress the warning and produce the intended visualization.


"""

plt.figure(figsize=(12, 6))
sns.barplot(x=hourly_entries.index, y=hourly_entries.values, hue=hourly_entries.index, palette='viridis', legend=False)
plt.title('Number of Vehicle Entries per Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Entries')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Summary:

### Q&A
*   What are the peak entry hours?
    The peak entry hour is 13 (1 PM), with 2657 entries.
*   How many entries are there per hour?
    The number of entries per hour ranges from 4 (at 22:00) to 2657 (at 13:00).

### Data Analysis Key Findings
*   The hour component was successfully extracted from the 'Intime' column, creating a new 'Entry Hour' column in the `ppc` DataFrame.
*   The number of vehicle entries per hour was calculated, showing entries distributed from 7:00 to 22:00.
*   The peak entry hour was identified as 13:00 (1 PM) with the highest count of 2657 entries.
*   Other hours with high entry counts include 14:00 with 2525 entries, 12:00 with 2333 entries, and 18:00 with 2296 entries.
*   A bar plot was successfully generated, effectively visualizing the number of vehicle entries across each hour of the day.

### Insights or Next Steps
*   The distinct peak at 13:00 suggests a significant mid-day surge in vehicle activity, which could be attributed to lunch breaks or a specific peak in business operations. This could inform staffing or resource allocation for peak hours.
*   Further analysis could investigate if this hourly pattern is consistent across different days of the week or specific event types, providing a more granular understanding of traffic flow.

"""



"""# Task
Analyze and visualize the distribution of user types for both entry ('Extra Inuser' column) and exit ('Extra Outuser' column) in the `ppc` DataFrame by calculating value counts for each column, displaying them, and creating bar plots to visualize their distributions, then summarize the findings, highlighting the most frequent user types for both entry and exit.

## Analyze 'Extra Inuser' column

### Subtask:
Calculate the value counts for the 'Extra Inuser' column and display them. Also, visualize the distribution using a bar plot to show the frequency of each 'Inuser' type.

**Reasoning**:
The subtask requires calculating the value counts for the 'Extra Inuser' column and visualizing them with a bar plot. I will start by calculating the value counts and then proceed to generate the bar plot as instructed.
"""

inuser_counts = ppc['Extra Inuser'].value_counts()
print("Distribution of 'Extra Inuser' types:")
display(inuser_counts)

plt.figure(figsize=(10, 6))
sns.barplot(x=inuser_counts.index, y=inuser_counts.values, hue=inuser_counts.index, palette='viridis', legend=False)
plt.title('Distribution of Extra Inuser Types')
plt.xlabel('Inuser Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Reasoning**:
The next step is to analyze the 'Extra Outuser' column. This involves calculating its value counts and visualizing the distribution with a bar plot, following the same pattern as the 'Extra Inuser' analysis to maintain consistency and fulfill the overall task requirements.


"""

outuser_counts = ppc['Extra Outuser'].value_counts()
print("Distribution of 'Extra Outuser' types:")
display(outuser_counts)

plt.figure(figsize=(10, 6))
sns.barplot(x=outuser_counts.index, y=outuser_counts.values, hue=outuser_counts.index, palette='magma', legend=False)
plt.title('Distribution of Extra Outuser Types')
plt.xlabel('Outuser Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Summary:

### Q&A
*   What are the most frequent 'Extra Inuser' types?
    'Operator 1' is the most frequent 'Extra Inuser' type with 8431 entries, followed by 'Operator 2' (6976 entries) and 'FASTag Based Automated Entry1' (6728 entries).
*   What are the most frequent 'Extra Outuser' types?
    'Operator 4' is the most frequent 'Extra Outuser' type with 15381 entries, followed by 'FASTag Based Automated Exit2' (5637 entries) and 'FASTag Based Automated Exit1' (1619 entries).

### Data Analysis Key Findings
*   **'Extra Inuser' Distribution:**
    *   The primary entry method is 'Operator 1' (8431 entries), indicating a significant manual or designated operator involvement at entry points.
    *   'Operator 2' and 'FASTag Based Automated Entry1' also contribute substantially to vehicle entries.
    *   'FASTag Based Automated Entry2' and 'Operator 4' have much lower counts, suggesting they are less common entry methods.
*   **'Extra Outuser' Distribution:**
    *   'Operator 4' is overwhelmingly the most common exit method, accounting for 15381 exits, which is more than double the next most frequent method.
    *   Automated FASTag exits ('FASTag Based Automated Exit2' and 'FASTag Based Automated Exit1') are the next most common exit methods.
    *   'Operator 1', 'Operator 2', and '(park360)' are rarely used for vehicle exits.

### Insights or Next Steps
*   **Operational Efficiency:** The high number of 'Operator' entries and exits suggests a significant human element in the parking process. Further analysis could explore the efficiency of these operations versus automated systems.
*   **Automation Potential:** While FASTag automated entries and exits are present, their volume is lower than operator-managed ones, especially for exits. This might indicate opportunities to encourage more automated processes to streamline traffic flow and reduce potential human error.
*   **User Experience:** Understanding the dominant entry and exit methods can inform improvements in signage, lane design, and system reliability to enhance the overall user experience.
*   **Anomaly Detection:** The very low counts for some operator types (e.g., 'Operator 2' for exit) might warrant investigation to ensure these are valid entries/exits and not data anomalies or miscategorizations.

## Final Task

### Subtask:
Summarize the findings for both 'Extra Inuser' and 'Extra Outuser' columns, highlighting the most frequent user types for both entry and exit, and discuss any insights from the analysis.

## Summary:

### Q&A
*   What are the most frequent 'Extra Inuser' types?
    'Operator 1' is the most frequent 'Extra Inuser' type with 8431 entries, followed by 'Operator 2' (6976 entries) and 'FASTag Based Automated Entry1' (6728 entries).
*   What are the most frequent 'Extra Outuser' types?
    'Operator 4' is the most frequent 'Extra Outuser' type with 15381 entries, followed by 'FASTag Based Automated Exit2' (5637 entries) and 'FASTag Based Automated Exit1' (1619 entries).

### Data Analysis Key Findings
*   **'Extra Inuser' Distribution:** The primary entry method is 'Operator 1' (8431 entries), indicating significant human or designated operator involvement at entry points. 'Operator 2' (6976 entries) and 'FASTag Based Automated Entry1' (6728 entries) are also substantial contributors to vehicle entries, while 'FASTag Based Automated Entry2' (534 entries) and 'Operator 4' (59 entries) are less common.
*   **'Extra Outuser' Distribution:** 'Operator 4' is the overwhelmingly most common exit method, accounting for 15381 exits, which is more than double the next most frequent method. Automated FASTag exits ('FASTag Based Automated Exit2' with 5637 entries and 'FASTag Based Automated Exit1' with 1619 entries) are the next most common, whereas 'Operator 1' (89 entries), 'Operator 2' (1 entry), and '(park360)' (1 entry) are rarely used for vehicle exits.

### Insights or Next Steps
*   The high prevalence of 'Operator 1' for entry and 'Operator 4' for exit suggests a significant human element in the parking process, indicating potential areas for efficiency improvement through automation.
*   The lower volume of FASTag automated entries and exits, especially compared to operator-managed ones, highlights an opportunity to encourage increased adoption of automated processes to streamline traffic flow and reduce human error.
"""

average_transaction_value = ppc['Amount'].mean()
print(f"Average Transaction Value: {average_transaction_value}")

revenue_by_vehicle_type = ppc.groupby('Vehicletype')['Amount'].sum()
print("Revenue by Vehicle Type:")
display(revenue_by_vehicle_type)

plt.figure(figsize=(10, 6))
sns.barplot(x=revenue_by_vehicle_type.index, y=revenue_by_vehicle_type.values, hue=revenue_by_vehicle_type.index, palette='viridis', legend=False)
plt.title('Revenue by Vehicle Type')
plt.xlabel('Vehicle Type')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

ppc['Entry Date'] = ppc['Intime'].dt.date
daily_transactions = ppc['Entry Date'].value_counts().sort_index()
print("Total Transactions per Day:")
display(daily_transactions)

fastag_revenue = ppc[ppc['Extra Paymenttype Out'] == 'FASTAG']['Amount'].sum()
print(f"FASTag Revenue: {fastag_revenue}")

cash_revenue = ppc[ppc['Extra Paymenttype Out'] == 'CASH']['Amount'].sum()
print(f"Cash Revenue: {cash_revenue}")

qr_revenue = ppc[ppc['Extra Paymenttype Out'] == 'QR']['Amount'].sum()
print(f"QR Revenue: {qr_revenue}")

total_invoices_generated = len(ppc['Invoiceno'].unique())
print(f"Total Invoices Generated: {total_invoices_generated}")

total_revenue = ppc['Amount'].sum()
unique_vehicles = ppc['Vehicleno'].nunique()
revenue_per_vehicle = total_revenue / unique_vehicles
print(f"Total Revenue: {total_revenue}")
print(f"Number of Unique Vehicles: {unique_vehicles}")
print(f"Revenue per Vehicle: {revenue_per_vehicle}")



"""## Total Revenue by Payment Method

*   **FASTag Revenue:** 731100
*   **Cash Revenue:** 950140
*   **QR Revenue:** 0
"""

payment_method_revenues = pd.DataFrame({
    'Payment Method': ['FASTAG', 'CASH', 'QR'],
    'Total Revenue': [fastag_revenue, cash_revenue, qr_revenue]
})

plt.figure(figsize=(10, 6))
sns.barplot(x='Payment Method', y='Total Revenue', data=payment_method_revenues, hue='Payment Method', palette='coolwarm', legend=False)
plt.title('Total Revenue by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()



"""## Extract exit hour

### Subtask:
Extract the hour from the 'Outtime' column and create a new column for it.

**Reasoning**:
The subtask is to extract the hour from the 'Outtime' column and store it in a new column called 'Exit Hour'. I will use the `.dt.hour` accessor for this.
"""

ppc['Exit Hour'] = ppc['Outtime'].dt.hour
print("Extracted 'Exit Hour' from 'Outtime' column.")
print(ppc[['Outtime', 'Exit Hour']].head())

"""## Calculate hourly exit counts

### Subtask:
Calculate the number of vehicle exits for each hour of the day.

**Reasoning**:
To calculate the number of vehicle exits for each hour of the day, I will group the DataFrame by 'Exit Hour' and count the occurrences in each group.
"""

hourly_exits = ppc.groupby('Exit Hour').size()
print("Number of vehicle exits per hour:")
display(hourly_exits)

"""## Identify peak exit hours

### Subtask:
Identify the hour(s) with the highest number of vehicle exits.

**Reasoning**:
To identify the peak exit hour(s), I need to find the maximum value in the `hourly_exits` Series and then retrieve the index (hour) associated with that maximum value.
"""

peak_exit_hours = hourly_exits[hourly_exits == hourly_exits.max()].index.tolist()
peak_exit_count = hourly_exits.max()
print(f"Peak exit hour(s): {peak_exit_hours} with {peak_exit_count} exits.")

